name: smart_trip_assistant
description: Plan smarter. Travel better.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
